### ISSUE TITLE
HalResponse.FromHttpResponse throws System.InvalidOperationException when an exception occurs and the status code is OK

### ISSUE THREAD

**Issue by anhaehne** [wertzui/HAL#2]
When an exception occurs during HalClient.SendAsync that which is not caused by a failed http request, the Response.StatusCode can be a success status code. `HalResponse.FromHttpResponse` then failes due to the success status code and hides the original exception.

Stacktrace:
```
System.InvalidOperationException: When providing problem details, the status code must not indicate a success. The given status code was OK.
   at HAL.Client.Net.HalResponse..ctor(ProblemDetails problemDetails, HttpStatusCode statusCode)
   at HAL.Client.Net.HalResponse`1..ctor(ProblemDetails problemDetails, HttpStatusCode statusCode)
   at HAL.Client.Net.HalResponse.FromHttpResponse[TState](HttpResponseMessage httpResponse, CancellationToken cancellationToken)
   at HAL.Client.Net.HalClient.SendAsync[TRequest,TResponse](HttpMethod method, Uri requestUri, TRequest content, IDictionary`2 uriParameters, IDictionary`2 headers, String version, CancellationToken cancellationToken)
```

**Comment by wertzui** [comment]
This has been fixed in HAL.Client.Net 8.0.0

In such cases the response contains the Status 422 Unprocessable Entity.
The included `ProblemDetails` contain the original Status code from the server.
